# @package _global_

defaults:
  - _self_
  - data: fastmri_multicoil # choose datamodule with `test_dataloader()` for evaluation
  - model: varnet
  - callbacks: default
  - logger: comet
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default
  - transforms: fastmri

  - experiment: fastmri_multicoil_knee_testing


task_name: "Evaluation"

tags: ["fastmri", "testing"]

logger:
  comet:
    project_name: "fastmri-multicoil-evaluation"

# passing checkpoint path is necessary for evaluation
ckpt_path: "/home/s2287251/data2/Users/Yuyang/Projects/ReconUnlearning/logs/Oracle/Oracle_ckpts/checkpoints/epoch_048_step_289002.ckpt"

seed: 42