# @package _global_

defaults:
  - _self_
  - data: knee_test # choose datamodule with `test_dataloader()` for evaluation
  - model: varnet
  - callbacks: default
  - logger: comet
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default
  - transforms: fastmri

task_name: "MRI_Recon_fastMRI_multicoil_finetuning"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: "/home/s2287251/idcom_imaging/Users/yuyang/VIOS-s/ReconUnlearning/logs/MRI_Recon_fastMRI_multicoil_mixed/runs/2024-01-11_16-30-11/checkpoints/epoch_049_step_1066450.ckpt"

seed: 42