# @package _global_

defaults:
  - _self_
  - data: fastmri_multicoil # choose datamodule with `test_dataloader()` for evaluation
  - model: varnet
  - callbacks: default
  - logger: comet
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default
  - transforms: fastmri

  - experiment: fastmri_multicoil_forget_testing


task_name: "Evaluation"

tags: ["fastmri", "testing"]

logger:
  comet:
    project_name: "fastmri-multicoil-evaluation"

# passing checkpoint path is necessary for evaluation
ckpt_path: "/localdisk/data2/Users/Yuyang/Projects/ReconUnlearning/logs/FineTuning/UL_0.1_GA_L1_FT/checkpoints/epoch_053_step_320856.ckpt"
seed: 42